apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: case4-3
data:
  NODE_ENV: "production"
  DB_SSL: "false"
  PORT: "3000"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "taskdb"
  DB_USERNAME: "postgres"
